### ISSUE TITLE
Release/Roadmap [Tracking]

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#203]
We have released a beta of 1.0.0. We continue to find edge cases to support/fix. 

## Release candidate 1.0.0-rc

- [x] [Incorrect `$ref`s](https://github.com/Redocly/openapi-cli/issues/189)
- [x] e2e tests
- [x] Separate core from CLI code (for usage in Redoc)
- [x] Try in Redoc
- [x] [Split command](https://github.com/Redocly/openapi-cli/issues/150)
- [x] Stats command
- [x] Collect feedback and fix edge cases
- [ ] Fix open bugs
- [ ] Review all naming of OpenAPI parts (such as PathItem, etc...)
- [ ] More built-in rules and decorators
- [ ] `.redocly.yaml` support for without the leading `.`
- [ ] `redocly.yaml` lint (self-check)
- [ ] `.redocly.yaml` review format for future plans to avoid future breaking changes

## General release 1.0.0

- [ ] Community plugins with registry
- [ ] More documentation
- [ ] Rename
- [ ] #292 Validate spec during preview
- [ ] DX tests on custom plugins/rules
- [x] Use in Redoc
- [ ] Fix open bugs
- [ ] Collect feedback and fix edge cases
- [x] OAS 3.1 support

## Later

- [ ] Discriminator checker https://github.com/Redocly/openapi-cli/issues/210
- [x] Join command
- [x] Push to registry command
- [ ] Convert command
- [ ] Fix command (to fix common mistakes generated by frameworks or converters)
- [ ] Diff

**Comment by adamaltman** [comment]
We're getting closer to a release candidate.

**Comment by lornajane** [comment]
Closing as outdated
