### ISSUE TITLE
Tracking issue

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#775]
### Configuration file changes

- [x] https://github.com/Redocly/redocly-cli/issues/697
- [x] https://github.com/Redocly/redocly-cli/issues/696
- [x] https://github.com/Redocly/redocly-cli/issues/714
- [x] https://github.com/Redocly/redocly-cli/issues/793
- [x] #833 
- [x] https://github.com/Redocly/redocly-cli/issues/839
- [x] https://github.com/Redocly/redocly-cli/pull/917
- [x] https://github.com/Redocly/redocly-cli/issues/900

After the breaking changes above, we can release a release candidate (e.g. 1.0.0-rc.1).

Goal: release by October 31st.

```mermaid
gantt
    title Possible release timeline
    dateFormat  YYYY-MM-DD
    section Breaking changes
    Config file changes           :2022-10-21, 10d
    section Release candidates
    Get community feedback      :2022-10-31  , 55d
    Revisions      : 24d
    General release : 1d
```

### Bugs
- [x] https://github.com/Redocly/redocly-cli/issues/767
- [x] https://github.com/Redocly/redocly-cli/issues/757
- [x] https://github.com/Redocly/redocly-cli/issues/702
- [x] https://github.com/Redocly/redocly-cli/issues/700
- [x] https://github.com/Redocly/redocly-cli/issues/750
- [x] https://github.com/Redocly/redocly-cli/issues/462
- [x] https://github.com/Redocly/redocly-cli/issues/424
- [x] #846
- [x] https://github.com/Redocly/redocly-cli/issues/211 

### Features/improvements
- [x] https://github.com/Redocly/redocly-cli/issues/481
- [x] https://github.com/Redocly/redocly-cli/issues/480
- [ ] https://github.com/Redocly/redocly-cli/issues/477
- [x] https://github.com/Redocly/redocly-cli/issues/392
- [x] https://github.com/Redocly/redocly-cli/issues/440
- [ ] https://github.com/Redocly/redocly-cli/issues/779
- [x] https://github.com/Redocly/redocly-cli/issues/780
- [ ] ignore to support wildcard paths
- [x] Add support for message placeholders in assertions

### Content

- [x] Split rules and decorators docs
- [ ] Rework custom plugin docs
- [ ] Blog posts

### Unrelated

- [x] https://github.com/Redocly/redocly-cli/issues/699
- [x] https://github.com/Redocly/redocly-cli/issues/732

**Comment by lornajane** [comment]
Closing since we're declaring the current code base stable and I think we have more or less everything on this list :tada:
